# Generated by Django 3.1.7 on 2021-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0002_auto_20210325_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
