# Generated by Django 3.1.7 on 2021-03-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is test discription', max_length=100),
            preserve_default=False,
        ),
    ]
