# Generated by Django 3.1.7 on 2021-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0006_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
