# Generated by Django 3.1.7 on 2021-04-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0011_auto_20210402_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amaount',
            new_name='amount',
        ),
    ]
