# Generated by Django 3.1.7 on 2021-04-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0012_auto_20210402_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
