# Generated by Django 3.1.7 on 2021-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0015_auto_20210405_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
