# Generated by Django 3.1.7 on 2021-04-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0018_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
